apiVersion : skaffold/v2beta26
kind : Config
build :
  local : 
    push : false 
  artifacts :
    - image : puranrana080/auth
      context : auth
      docker :
        dockerfile : Dockerfile
      sync :
        manual : 
          - src : 'src/**/*.ts'
            dest: .
    - image: puranrana080/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image : puranrana080/tickets
      context : tickets
      docker :
        dockerfile : Dockerfile
      sync :
        manual : 
          - src : 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*